# Defines an additional hardened port, 122.

# It's a bit ugly that we define the default port here, but if we didn't
# then `Port 122` by itself would result in port 22 being disabled.
Port 22

# The additional port and rules.
Port 122
Match LocalPort 122
    GSSAPIAuthentication no
    KbdInteractiveAuthentication no
    PasswordAuthentication no
    PermitRootLogin no
Match all
