#!/usr/bin/env bash

set -ex

SOURCE_PATH="/var/opt/zeroclaw"
SNAPSHOT_PATH="${SOURCE_PATH}.snapshot"

function cleanup() {
  if [ -d "${SNAPSHOT_PATH}" ]; then
    btrfs subvolume delete "${SNAPSHOT_PATH}"
  fi
}

cleanup
trap cleanup EXIT

btrfs subvolume snapshot -r "${SOURCE_PATH}" "${SNAPSHOT_PATH}"

/usr/libexec/restic-backup "${SNAPSHOT_PATH}" zeroclaw daily zeroclaw
